### ISSUE TITLE
temperatures 1.5-2°C higher than original repo from Peter Dahlberg

### ISSUE THREAD

**Issue by nkrba** [robert-hh/BME280#15]
hello,
temperature values from `bme280_float.py` or `bme280_int.py` are 1.5-2°C higher than from `bme280.py` of https://github.com/catdog2/mpy_bme280_esp8266

differences were consistent with `mode=1` or `4` or `5` explicitly set, as the default `mode` is different in the two repos; tested at 20-28°C

the logic does seem slightly different between the two repos, so wanted to confirm by reporting here
the datasheets referenced are slightly different too, with revisions 1.1 and 1.24

**Comment by robert-hh** [comment]
Thank you for your post. I know that the implementations are slightly different, because I changed them. following carefully the reference implementation of Bosch.

The problem for me was, that I usually cannot fully trust that the breakout board I got has a genuine and calibrated sensor. And I did have only once a calibrated temperature sensor as reference.

At least, I made in December 2018 a series of measurements with different sensors (DHT22, SI7021, BME280, BME680) with the primary focus of the humidity values when exposed to well defined conditions. But I captured the temperature reading as well, because that's important for rel. humidity. The tempersture was usually at 20*-22°C, with one series at 3.5°C (outside).  All sensors temperature reading were within a difference of <0.5°C between the sensor with the lowest reading and the one with the highest. The DHT22, SI7021 and BME280 usually differed by not more than 0.2°C, the BME680 showed always like 0.3 - 0.5°C higher values than the others. All sensors are specified with an error of +/- 0.5°C for temperature. So it all looks well, and it provides some confidence that the code is right.
I just compared the BME680 use for the above test series with a DS18B20 (because I have them ready to connect), and the BME680 shows a 0.3°C higher value than the DS18X20.

**Comment by nkrba** [comment]
thank you for the response and your work for the open source community!

i have been having the same issue too, reg calibration - how does one get such a calibrated temperature/humidity sensor as you had obtained?

for me the lower values of BME280 (using Peter Dahlberg's repo) are matching (+/- 0.5°C but almost always its a + with BME reporting higher) an independent instrument, "HTC-1 Digital Thermometer Hygrometer Clock Alarm", but matching only for temperature. humidity of HTC-1 is almost always 10-15% lower than BME280.

and also tested with a DHT22, whose temperatures are almost always 2-3°C more than BME280 (hence values using your repo are a closer match here indeed) but humidity is almost always 15-25% higher than BME280.

in such a scenario, it behoves me to simply trust one of the sensors and call it a closure after multiple trials across several months. may be you are already aware of these pages below, but it helped me understand such testing procedures that you'd done and naturally began to trust the BME280 and DHT22 - which is why i bought them only after my sensor research. but even after investing the money, effort and time, it seems we have to just believe in Spinoza's God, like Einstein, and trust a particular sensor from experience across the community maybe (?):

https://www.kandrsmith.org/RJS/Misc/Hygrometers/calib_many.html
https://www.kandrsmith.org/RJS/Misc/Hygrometers/absolutetemperature.html

**Comment by robert-hh** [comment]
I have similar HTC Digital hygrometer/temperature devices, one of them close to my desk. These always showed slightly different temperatures, until I taped the temperature sensor under test to the HTC and moved them together to a place far away from my computer and me. Then the readings were much more close. It was interesting that there were temperatures differences in a room even at short distances.

I made my humidity tests with a similar set-up of the tests you linked with all sensor types being together in a closed box including a  small ventilator. With that set-up the temperature was pretty much the same for all sensors. So at least the comparison should be valid.

> how does one get such a calibrated temperature/humidity sensor as you had obtained?

You can use any device, only it has to be certified. We had to dedicated temperature measurement devices at out office for reference. They were sent annually for calibration to a certified calibration lab.
