### ISSUE TITLE
Reading errors when BME280 is on about 0 degrees Celsius 

### ISSUE THREAD

**Issue by sw-dev-code** [robert-hh/BME280#4]
BME280 reading shows a lot of instability when sensor is placed in environment where temperature is about or below zero degrees. Pictures of results is in the attachment. 

![thumbnail_image (1)](https://user-images.githubusercontent.com/13959599/73496050-0a0eb180-43b8-11ea-95bb-fce8173d54c4.png)
![thumbnail_image](https://user-images.githubusercontent.com/13959599/73496051-0a0eb180-43b8-11ea-8b57-7ddebd3da5e5.png)

Does anyone can help with this issue?

**Comment by robert-hh** [comment]
It looks like you observe a physical phenomenon of condensing and vaporizing humidity. I do not know how you influence the environment of the device, or whether you use it to switch something on  and off. If the cycling is caused by an external reason, then it's just something to notice. If you just have the sensor measuring, you mitgh try the latest update of the firmware, which changed the operating mode of the sensor to 'normal', meaning that it is switched off between test cycles.

**Comment by sw-dev-code** [comment]
@robert-hh I'm not sure I understand you completely. Device is used for environment monitoring, so I just read the data from BLE280 and sending it to the cloud. When you say to try latest update of the firmware, are you thinking of this BLE280 micropython library?

One more thing, what do you mean when you say cycling?

Thanks for the help.

**Comment by robert-hh** [comment]
I do not know where you placed the sensor, if just outside or in something like a fridge for testing.
What I see after a fast drop at about 14:46 at about 18:39 a periodic event starting with about 1 hour period. In that time the temperature starts rising slowly, until it drops fast, as if some cooling machine started, and stopped at reaching the lower point again. A little bit unexpected is, that the humidity falls with the temperature, but that may be caused by the water freezing out of the air below 0.
Please consider also, that freezing water releases energy. 
So I guess it#s not the BME280, which is unstable, but just some thermal phenomenon you see at this just-below-zero temperature.
And yes, by recommending to use the latest update I mean this library.

**Comment by sw-dev-code** [comment]
This figures is when device was in fridge for testing, but we also have this problem with devices that are on the field. So, this problem is just result of enviromental phenomenon?
I'm using latest library.

Thank you for your time and explanation.
