### ISSUE TITLE
Correction of documentation / guide...?

### ISSUE THREAD

**Issue by CesiumK9** [robert-hh/BME280#7]
Good day robert-hh...

This past week I've tinkering with BME280 and came across this lib...

It's works, but the readme.md had me perplexed for a while. I need 'bme280.sealevel'...

Perhaps 'bmp.' should be corrected to ' bme280.'....?

**Comment by robert-hh** [comment]
Thanks. These are just copy & paste errors from the BMP085, BMP180 driver. I'll fix that. Obviously, it is bme instead of bmp for the documentations. In your code, you can give the instance of BME280 any name, like `sensor = BME280(....)`. Then the calls would be:
`sensor.sealevel(.....)`  and
`sensor.values`
